trigger:
  branches:
    include:
      - main
      - green

pool:
  vmImage: 'ubuntu-latest'

variables:
  ResourceGroupName: 'webapp'
  WEBAPP_NAME: 'mywebsite8855'
  WEBAPP_PLAN: 'ASP-site1-ac69'
  REGION: 'westus3'
  azureSubscription: 'webapp'
  GREEN_SLOT: 'green'

steps:

# -----------------------------
# Build / Archive Application
# -----------------------------
- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


# =========================================
# MAIN BRANCH → PRODUCTION
# =========================================
- task: AzureWebApp@1
  displayName: 'Deploy Main Branch to Production'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(WEBAPP_NAME)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'


# =========================================
# GREEN BRANCH → GREEN SLOT
# =========================================
- task: AzureWebApp@1
  displayName: 'Deploy Green Branch to Green Slot'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/green')
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(WEBAPP_NAME)'
    deployToSlotOrASE: true
    resourceGroupName: '$(ResourceGroupName)'
    slotName: '$(GREEN_SLOT)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
